Guy Montag;Mildred Montag;
Captain Beatty;Guy Montag;
Professor Faber;Guy Montag;
Clarisse McClellan;Guy Montag;
Granger;Guy Montag;
Mrs. Phelps;Mildred Montag;
Mrs. Phelps;Guy Montag;
Mrs. Bowles;Mildred Montag;
Stoneman;Guy Montag;
Black;Guy Montag;
Stoneman;Black;
