John;The Director;
John;Linda;
Helmholtz Watson;Bernard Marx;
Lenina Crowne;Bernard Marx;
Lenina Crowne;John;
Fanny Crowne;Lenina Crowne;
Henry Foster;Lenina Crowne;
Henry Foster;Bernard Marx;
The Director;Bernard Marx;
Pope;Linda;
