Homer Simpson;Faye Greener;
Faye Greener;Harry Greener;
Earle Shoop;Faye Greener;
Miguel;Earle Shoop;
Miguel;Faye Greener;
Honest Abe Kusich;Tod Hackett;
Honest Abe Kusich;Faye Greener;
Claude Estee;Tod Hackett;
Alice Estee;Claude Estee;
Maybelle Loomis;Homer Simpson;
Maybelle Loomis;Adore Loomis;
Mary Dove;Faye Greener;
Mary Dove;Audrey Jenning;
Calvin;Earle Shoop;
Hink;Calvin;
Hink;Earle Shoop;
Romola Martin;Homer Simpson;
