Lennie;George;
Candy;George;
Candy;Lennie;
Curley's wife;Lennie;
Curley's wife;Candy;
Curley's wife;Crooks;
Crooks;Lennie;
Crooks;George;
Curley;Curley's wife;
Curley;Lennie;
Curley;George;
Slim;Candy;
Slim;George;
Carlson;Candy;
The Boss;Curley;
Aunt Clara;Lennie;
