Ahab;Moby Dick;
Ahab;Pip;
Starbuck;Ahab;
Queequeg;Starbuck;
Queequeg;Ishmael;
Stubb;Ahab;
Stubb;Tashtego;
Flask;Ahab;
Daggoo;Flask;
Fedallah;Ahab;
Peleg;Bildad;
Captain Boomer;Moby Dick;
Captain Boomer;Ahab;
