Dr. Aziz;Miss Adela Quested;
Dr. Aziz;Mrs. Moore;
Dr. Aziz;Cyril Fielding;
Miss Adela Quested;Mrs. Moore;
Miss Adela Quested;Ronny Heaslop;
Mr. Turton;Mrs. Turton;
Mr. McBryde;Cyril Fielding;
Mr. McBryde;Miss Derek;
Major Callendar;Dr. Aziz;
Professor Godbole;Cyril Fielding;
Hamidullah;Dr. Aziz;
Hamidullah;Cyril Fielding;
Mahmoud Ali;Dr. Aziz;
The Nawab Bahadur;Dr. Aziz;
Dr. Panna Lal;Dr. Aziz;
Stella Moore;Mrs. Moore;
Stella Moore;Cyril Fielding;
Ralph Moore;Mrs. Moore;
Amritrao;Dr. Aziz;
